### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by samuelmburu** [tomsowerby/starred-package-installer#8]
[Enter steps to reproduce below:]
1. clicked download package from inside atom settings>install packages
2. Error popped up

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [starred-package-installer](https://github.com/tomsowerby/starred-package-installer) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
  at /Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:6:3
  at Object.<anonymous> (/Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:84:5)
  at Object.<anonymous> (/Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:31)
  at Object.<anonymous> (/Users/samuelmburu/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:168:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:588:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:379:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "accents-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
accents-ui, v1.0.0
atom-beautify, v0.28.14
atom-jade, v0.3.0
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.10
jshint, v1.8.0
linter, v1.8.1
linter-tidy, v1.0.1
wakatime, v5.0.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by davej** [comment]
Getting same error on Atom 1.1.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [starred-package-installer](https://github.com/tomsowerby/starred-package-installer) package, v0.1.0

### Stack Trace

Failed to load the starred-package-installer package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/dave/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
  at /Users/dave/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:6:3
  at Object.<anonymous> (/Users/dave/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:84:5)
  at Object.<anonymous> (/Users/dave/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/dave/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:31)
  at Object.<anonymous> (/Users/dave/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:363:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "atom-live-grammar-reload",
      "atom-live-grammar-reload",
      "atom-live-grammar-reload",
      "atom-live-grammar-reload",
      "git-control",
      "typescript-atomizer",
      "language-applescript"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": false
  }
}
```

### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-cli-diff, v1.1.0
atom-jade, v0.3.0
coffee-compile, v0.19.2
docblockr, v0.7.3
emmet, v2.3.14
imdone-atom, v1.1.53
language-earl-grey, v0.10.0
language-elixir, v0.5.2
language-erlang, v3.0.0
language-javascript-jsx, v0.3.7
linter, v1.10.0
linter-jshint, v1.2.1
remote-atom, v1.2.9
seti-ui, v0.8.1
starred-package-installer, v0.1.0

# Dev
No dev packages
```
