### ISSUE TITLE
Failed to load the starred-package-installer package

### ISSUE THREAD

**Issue by windycitymoon** [tomsowerby/starred-package-installer#9]
[Enter steps to reproduce below:]
1. ...Attempt to load starred-package-installer from Atom Installer GUI
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [starred-package-installer](https://github.com/tomsowerby/starred-package-installer) package, v0.1.0
### Stack Trace

Failed to load the starred-package-installer package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/dmoon/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
    at /Users/dmoon/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:6:3
    at Object.<anonymous> (/Users/dmoon/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:6:3)
    at Object.<anonymous> (/Users/dmoon/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/dmoon/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:31)
    at Object.<anonymous> (/Users/dmoon/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
emmet, v2.4.2
grunt-runner, v0.14.0
javascript-snippets, v1.2.1
livestyle-atom, v0.1.3
minimap, v4.20.0
starred-package-installer, v0.1.0

# Dev
No dev packages
```

**Comment by 24Degrees** [comment]
Same problem here...

**Comment by JeffGreenlee42** [comment]
Ditto for me... will this be fixed?

**Comment by JeffGreenlee42** [comment]
Wish this would be fixed so I don't keep seeing this warning message everytime I open Atom!

**Comment by windycitymoon** [comment]
I've found another way to proceed. I uninstalled this plugin and used atom's default package manger, apm. That lets you install your starred packages.

just run 
``apm stars --install``

**Comment by JeffGreenlee42** [comment]
ok thank.

Jeff Greenlee

"Music is Love in search of a voice."
Leo Tolstoy
